development:
  domain: localhost:3000
  sitename: つぶやき＠名無し（開発）
  twitter:
    app_user: dev_func09
    hashtag: '#nanasi'
test:
  domain: test.host

production:
  domain: nanasi3.com
  sitename: つぶやき＠名無し
  twitter:
    app_user: nanasi_3
    hashtag: '#nanasi'
